{% set name = "fps-noauth" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_noauth-{{ version }}.tar.gz
  sha256: 75c08c6ee2083f973acf4fd9ca83b16ffb384be8bc4ee484991b20b2e65b2da6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - fps >=0.0.8,<1

test:
  imports:
    - fps_noauth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/noauth
  summary: An FPS plugin for an unprotected API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/noauth
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
