{% set name = "fps-noauth" %}
{% set version = "0.0.48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_noauth-{{ version }}.tar.gz
  sha256: 224a9641c04f02da6ada0f9653107e92614862e0a48b0e7b2498d37f1584de3b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - fps >=0.0.8,<1

test:
  imports:
    - fps_noauth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/noauth
  summary: An FPS plugin for an unprotected API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/noauth
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
