{% set name = "fps-noauth" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_noauth-{{ version }}.tar.gz
  sha256: cb596f5ddaf4dec7358747def64879044c4c629c769fcf1ad45482ba5bc02f4c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.7.0,<1

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_noauth

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/noauth
  summary: An FPS plugin for an unprotected API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/noauth
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
